### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by ggalan87** [Rachnog/disentanglment#1]
First of all thank you for your article+provided code.

Can you also upload the corresponding data, as the original [site](https://physionet.org/physiobank/database/ptbdb/) does not provide npy files.

Thank's in advance.

**Comment by Rachnog** [comment]
Fair enough :)
Here is the dataset itself: https://drive.google.com/file/d/1Ay0mIy-lhs1jLAbtIHeHC0vHuX64u08J/view?usp=sharing
